// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: idserv.proto

package idserv

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The client sends a unique id.
type IdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
}

func (x *IdRequest) Reset() {
	*x = IdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idserv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdRequest) ProtoMessage() {}

func (x *IdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idserv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdRequest.ProtoReflect.Descriptor instead.
func (*IdRequest) Descriptor() ([]byte, []int) {
	return file_idserv_proto_rawDescGZIP(), []int{0}
}

func (x *IdRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// The response message contains the uuid.
type IdReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *IdReply) Reset() {
	*x = IdReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idserv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdReply) ProtoMessage() {}

func (x *IdReply) ProtoReflect() protoreflect.Message {
	mi := &file_idserv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdReply.ProtoReflect.Descriptor instead.
func (*IdReply) Descriptor() ([]byte, []int) {
	return file_idserv_proto_rawDescGZIP(), []int{1}
}

func (x *IdReply) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

var File_idserv_proto protoreflect.FileDescriptor

var file_idserv_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x69, 0x64, 0x73, 0x65, 0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x69, 0x64, 0x73, 0x65, 0x72, 0x76, 0x22, 0x27, 0x0a, 0x09, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22,
	0x1d, 0x0a, 0x07, 0x49, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x32, 0x3c,
	0x0a, 0x09, 0x49, 0x44, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2f, 0x0a, 0x07, 0x4e,
	0x65, 0x77, 0x55, 0x55, 0x49, 0x44, 0x12, 0x11, 0x2e, 0x69, 0x64, 0x73, 0x65, 0x72, 0x76, 0x2e,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x69, 0x64, 0x73, 0x65,
	0x72, 0x76, 0x2e, 0x49, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08,
	0x2e, 0x2f, 0x69, 0x64, 0x73, 0x65, 0x72, 0x76, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_idserv_proto_rawDescOnce sync.Once
	file_idserv_proto_rawDescData = file_idserv_proto_rawDesc
)

func file_idserv_proto_rawDescGZIP() []byte {
	file_idserv_proto_rawDescOnce.Do(func() {
		file_idserv_proto_rawDescData = protoimpl.X.CompressGZIP(file_idserv_proto_rawDescData)
	})
	return file_idserv_proto_rawDescData
}

var file_idserv_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_idserv_proto_goTypes = []interface{}{
	(*IdRequest)(nil), // 0: idserv.IdRequest
	(*IdReply)(nil),   // 1: idserv.IdReply
}
var file_idserv_proto_depIdxs = []int32{
	0, // 0: idserv.IDService.NewUUID:input_type -> idserv.IdRequest
	1, // 1: idserv.IDService.NewUUID:output_type -> idserv.IdReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_idserv_proto_init() }
func file_idserv_proto_init() {
	if File_idserv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_idserv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idserv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idserv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idserv_proto_goTypes,
		DependencyIndexes: file_idserv_proto_depIdxs,
		MessageInfos:      file_idserv_proto_msgTypes,
	}.Build()
	File_idserv_proto = out.File
	file_idserv_proto_rawDesc = nil
	file_idserv_proto_goTypes = nil
	file_idserv_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// IDServiceClient is the client API for IDService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IDServiceClient interface {
	// NewUUID generates a globally unique ID
	NewUUID(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*IdReply, error)
}

type iDServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIDServiceClient(cc grpc.ClientConnInterface) IDServiceClient {
	return &iDServiceClient{cc}
}

func (c *iDServiceClient) NewUUID(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*IdReply, error) {
	out := new(IdReply)
	err := c.cc.Invoke(ctx, "/idserv.IDService/NewUUID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IDServiceServer is the server API for IDService service.
type IDServiceServer interface {
	// NewUUID generates a globally unique ID
	NewUUID(context.Context, *IdRequest) (*IdReply, error)
}

// UnimplementedIDServiceServer can be embedded to have forward compatible implementations.
type UnimplementedIDServiceServer struct {
}

func (*UnimplementedIDServiceServer) NewUUID(context.Context, *IdRequest) (*IdReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewUUID not implemented")
}

func RegisterIDServiceServer(s *grpc.Server, srv IDServiceServer) {
	s.RegisterService(&_IDService_serviceDesc, srv)
}

func _IDService_NewUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IDServiceServer).NewUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idserv.IDService/NewUUID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IDServiceServer).NewUUID(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IDService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "idserv.IDService",
	HandlerType: (*IDServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewUUID",
			Handler:    _IDService_NewUUID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idserv.proto",
}
