#!/usr/bin/env sh

clear
cat "$(dirname $0)/ascii-art.txt"

export SEU_HOME="/Volumes/COPL"
export GOROOT="$SEU_HOME/software/goroot"
export GOPATH="$SEU_HOME/codebase"
export GOBIN="$SEU_HOME/codebase/bin"
export PATH="$GOBIN:$GOROOT/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

export ZDOTDIR="$SEU_HOME"
cd $SEU_HOME/codebase/src
