#!/usr/bin/env sh

clear
cat "$(dirname $0)/ascii-art.txt"

export SEU_HOME="/Volumes/COPL"
export GOPATH="$SEU_HOME/codebase"
export GOBIN="$SEU_HOME/codebase/bin"
export PATH="$GOBIN:$GOROOT/bin:$PATH"

export ZDOTDIR="$SEU_HOME"
cd $SEU_HOME/codebase/src
